/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;

import java.awt.Color;

/**
 *
 * @author hp
 */
public class Question2 extends javax.swing.JFrame {

    /**
     * Creates new form Question2
     */
    public Question2() {
        initComponents();
         this.getContentPane().setBackground(Color.YELLOW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        a1 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        a4 = new javax.swing.JRadioButton();
        a5 = new javax.swing.JRadioButton();
        a6 = new javax.swing.JRadioButton();
        a7 = new javax.swing.JRadioButton();
        a8 = new javax.swing.JRadioButton();
        a9 = new javax.swing.JRadioButton();
        a10 = new javax.swing.JRadioButton();
        a11 = new javax.swing.JRadioButton();
        a12 = new javax.swing.JRadioButton();
        a13 = new javax.swing.JRadioButton();
        a14 = new javax.swing.JRadioButton();
        a15 = new javax.swing.JRadioButton();
        a16 = new javax.swing.JRadioButton();
        a17 = new javax.swing.JRadioButton();
        a18 = new javax.swing.JRadioButton();
        a19 = new javax.swing.JRadioButton();
        a20 = new javax.swing.JRadioButton();
        a21 = new javax.swing.JRadioButton();
        a22 = new javax.swing.JRadioButton();
        a23 = new javax.swing.JRadioButton();
        a24 = new javax.swing.JRadioButton();
        a25 = new javax.swing.JRadioButton();
        a26 = new javax.swing.JRadioButton();
        a27 = new javax.swing.JRadioButton();
        a28 = new javax.swing.JRadioButton();
        a29 = new javax.swing.JRadioButton();
        a30 = new javax.swing.JRadioButton();
        a31 = new javax.swing.JRadioButton();
        a32 = new javax.swing.JRadioButton();
        a41 = new javax.swing.JRadioButton();
        a42 = new javax.swing.JRadioButton();
        a43 = new javax.swing.JRadioButton();
        a44 = new javax.swing.JRadioButton();
        a45 = new javax.swing.JRadioButton();
        a46 = new javax.swing.JRadioButton();
        a47 = new javax.swing.JRadioButton();
        a48 = new javax.swing.JRadioButton();
        a49 = new javax.swing.JRadioButton();
        a50 = new javax.swing.JRadioButton();
        a51 = new javax.swing.JRadioButton();
        a52 = new javax.swing.JRadioButton();
        a53 = new javax.swing.JRadioButton();
        a54 = new javax.swing.JRadioButton();
        a55 = new javax.swing.JRadioButton();
        a56 = new javax.swing.JRadioButton();
        a57 = new javax.swing.JRadioButton();
        a58 = new javax.swing.JRadioButton();
        a59 = new javax.swing.JRadioButton();
        a60 = new javax.swing.JRadioButton();
        a61 = new javax.swing.JRadioButton();
        a62 = new javax.swing.JRadioButton();
        a63 = new javax.swing.JRadioButton();
        a64 = new javax.swing.JRadioButton();
        a65 = new javax.swing.JRadioButton();
        a66 = new javax.swing.JRadioButton();
        a67 = new javax.swing.JRadioButton();
        a68 = new javax.swing.JRadioButton();
        a69 = new javax.swing.JRadioButton();
        a70 = new javax.swing.JRadioButton();
        a71 = new javax.swing.JRadioButton();
        a72 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        a33 = new javax.swing.JRadioButton();
        a34 = new javax.swing.JRadioButton();
        a35 = new javax.swing.JRadioButton();
        a36 = new javax.swing.JRadioButton();
        a37 = new javax.swing.JRadioButton();
        a38 = new javax.swing.JRadioButton();
        a39 = new javax.swing.JRadioButton();
        a40 = new javax.swing.JRadioButton();
        a73 = new javax.swing.JRadioButton();
        a74 = new javax.swing.JRadioButton();
        a75 = new javax.swing.JRadioButton();
        a76 = new javax.swing.JRadioButton();
        a77 = new javax.swing.JRadioButton();
        a78 = new javax.swing.JRadioButton();
        a79 = new javax.swing.JRadioButton();
        a80 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(a1);
        a1.setText("java.io");

        buttonGroup1.add(a2);
        a2.setText("java.system");

        buttonGroup1.add(a3);
        a3.setText("java.lang");

        buttonGroup1.add(a4);
        a4.setText("java.util");

        buttonGroup2.add(a5);
        a5.setText(" Compilation");

        buttonGroup2.add(a6);
        a6.setText("throw");

        buttonGroup2.add(a7);
        a7.setText("catch");

        buttonGroup2.add(a8);
        a8.setText(" try");

        buttonGroup3.add(a9);
        a9.setText(" 0 to 256");

        buttonGroup3.add(a10);
        a10.setText(" 0 to 65535");

        buttonGroup3.add(a11);
        a11.setText("-128 to 127");

        buttonGroup3.add(a12);
        a12.setText("0 to 32767");

        buttonGroup4.add(a13);
        a13.setText("ServerSocket");

        buttonGroup4.add(a14);
        a14.setText("Socket");

        buttonGroup4.add(a15);
        a15.setText("ServerReader");

        buttonGroup4.add(a16);
        a16.setText("Server");

        buttonGroup5.add(a17);
        a17.setText("-1.7e+308");

        buttonGroup5.add(a18);
        a18.setText("-3.4e+037");

        buttonGroup5.add(a19);
        a19.setText("-3.4e+038");

        buttonGroup5.add(a20);
        a20.setText("-3.4e+050");

        buttonGroup6.add(a21);
        a21.setText("float");

        buttonGroup6.add(a22);
        a22.setText("long");

        buttonGroup6.add(a23);
        a23.setText("double");

        buttonGroup6.add(a24);
        a24.setText("int");

        buttonGroup7.add(a25);
        a25.setText("int");

        buttonGroup7.add(a26);
        a26.setText("float");

        buttonGroup7.add(a27);
        a27.setText("double");

        buttonGroup7.add(a28);
        a28.setText("void");

        buttonGroup8.add(a29);
        a29.setText("Function overriding");

        buttonGroup8.add(a30);
        a30.setText("Function overloading");
        a30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a30ActionPerformed(evt);
            }
        });

        buttonGroup8.add(a31);
        a31.setText("Function doubling");

        buttonGroup8.add(a32);
        a32.setText("none");

        buttonGroup11.add(a41);
        a41.setText("1");

        buttonGroup11.add(a42);
        a42.setText("2");

        buttonGroup11.add(a43);
        a43.setText("4");

        buttonGroup11.add(a44);
        a44.setText("7");

        buttonGroup12.add(a45);
        a45.setText("Dynamic ");

        buttonGroup12.add(a46);
        a46.setText("jRadioButton1");

        buttonGroup12.add(a47);
        a47.setText("Architecture Neutral");

        buttonGroup12.add(a48);
        a48.setText("Use of pointers");

        buttonGroup13.add(a49);
        a49.setText("JVM");

        buttonGroup13.add(a50);
        a50.setText("JDB");

        buttonGroup13.add(a51);
        a51.setText("JRE");

        buttonGroup13.add(a52);
        a52.setText("jRadioButton1");

        buttonGroup14.add(a53);
        a53.setText("char ch = '\\utea';");

        buttonGroup14.add(a54);
        a54.setText("char ca = 'tea';");

        buttonGroup14.add(a55);
        a55.setText("char cr = \\u0223;");

        buttonGroup14.add(a56);
        a56.setText("jRadioButton1");

        buttonGroup15.add(a57);
        a57.setText("void");

        buttonGroup15.add(a58);
        a58.setText("long");

        buttonGroup15.add(a59);
        a59.setText("int");

        buttonGroup15.add(a60);
        a60.setText("Object");

        buttonGroup16.add(a61);
        a61.setText("L990023");

        buttonGroup16.add(a62);
        a62.setText("904423");

        buttonGroup16.add(a63);
        a63.setText("0xnf029L");

        buttonGroup16.add(a64);
        a64.setText("ABH8097");

        buttonGroup17.add(a65);
        a65.setText("0");

        buttonGroup17.add(a66);
        a66.setText("Not a Number");

        buttonGroup17.add(a67);
        a67.setText("Run time exception");

        buttonGroup17.add(a68);
        a68.setText("Infinity");

        buttonGroup18.add(a69);
        a69.setText("java.lang package");

        buttonGroup18.add(a70);
        a70.setText("java.util package");

        buttonGroup18.add(a71);
        a71.setText("java.lang package");

        buttonGroup18.add(a72);
        a72.setText("java.io package");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup9.add(a33);
        a33.setText("constructor");

        buttonGroup9.add(a34);
        a34.setText("class");

        buttonGroup9.add(a35);
        a35.setText("delete");

        buttonGroup9.add(a36);
        a36.setText(" finalize");

        buttonGroup10.add(a37);
        a37.setText("finalize method");

        buttonGroup10.add(a38);
        a38.setText("finalize method");

        buttonGroup10.add(a39);
        a39.setText("main method");

        buttonGroup10.add(a40);
        a40.setText("finalize method");

        buttonGroup19.add(a73);
        a73.setText("Applet class");

        buttonGroup19.add(a74);
        a74.setText("Window class");

        buttonGroup19.add(a75);
        a75.setText("Frame class");

        buttonGroup19.add(a76);
        a76.setText("Dialog class");

        buttonGroup20.add(a77);
        a77.setText("Stack");

        buttonGroup20.add(a78);
        a78.setText("String memory");

        buttonGroup20.add(a79);
        a79.setText("Heap memory");

        buttonGroup20.add(a80);
        a80.setText("Random storage space");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("1.Which of these packages contains the exception Stack Overflow in Java?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("2.Which of these keywords are used for the block to be examined for exceptions?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("3.What is the numerical range of a char data type in Java?");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("4.Which class provides system independent server side implementation?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("5.Which of these literals can be contained in float data type variable?");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("6. Which data type value is returned by all transcendental math functions?");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("7.What is the return type of a method that does not return any value?");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("8. What is the process of defining more than one method in a class differentiated by method signature?");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("9.Which of the following is a method having same name as that of it’s class? ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("10.Which method can be defined only once in a program?");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("11.NUmber of loops in Java?");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("12. Which of the following is not a Java features?");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("13._____ is used to find and fix bugs in the Java programs.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("14. Which of the following is a valid declaration of a char?");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("15.What is the return type of the hashCode() method in the Object class?");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("16.Which of the following is a valid long literal?");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("17.What does the expression float a = 35 / 0 return?");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("18.Which package contains the Random class?");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("19.Which of the following is an immediate subclass of the Panel class?");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setText("20. In which memory a String is stored, when we create a string using new operator?");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel21.setText("   JAVA QUESTIONS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(a29)
                                        .addGap(18, 18, 18)
                                        .addComponent(a30)
                                        .addGap(18, 18, 18)
                                        .addComponent(a31)
                                        .addGap(38, 38, 38)
                                        .addComponent(a32))
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a33)
                                        .addGap(18, 18, 18)
                                        .addComponent(a34)
                                        .addGap(26, 26, 26)
                                        .addComponent(a35)
                                        .addGap(18, 18, 18)
                                        .addComponent(a36))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a37)
                                        .addGap(18, 18, 18)
                                        .addComponent(a38)
                                        .addGap(18, 18, 18)
                                        .addComponent(a39)
                                        .addGap(18, 18, 18)
                                        .addComponent(a40))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(91, 91, 91)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a3)
                                        .addGap(27, 27, 27)
                                        .addComponent(a4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a21)
                                        .addGap(30, 30, 30)
                                        .addComponent(a22)
                                        .addGap(18, 18, 18)
                                        .addComponent(a23)
                                        .addGap(18, 18, 18)
                                        .addComponent(a24))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(a25)
                                .addGap(30, 30, 30)
                                .addComponent(a26)
                                .addGap(26, 26, 26)
                                .addComponent(a27)
                                .addGap(28, 28, 28)
                                .addComponent(a28))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a6)
                                        .addGap(18, 18, 18)
                                        .addComponent(a7)
                                        .addGap(18, 18, 18)
                                        .addComponent(a8))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a12))
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a13)
                                        .addGap(8, 8, 8)
                                        .addComponent(a14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a15)
                                        .addGap(28, 28, 28)
                                        .addComponent(a16))
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(a17)
                                .addGap(18, 18, 18)
                                .addComponent(a18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a19)
                                .addGap(18, 18, 18)
                                .addComponent(a20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(a65)
                                .addGap(18, 18, 18)
                                .addComponent(a66)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a67)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a68))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(a41)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(a42)
                                            .addGap(18, 18, 18)
                                            .addComponent(a43)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(a44))
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a49)
                                        .addGap(28, 28, 28)
                                        .addComponent(a50)
                                        .addGap(33, 33, 33)
                                        .addComponent(a51)
                                        .addGap(41, 41, 41)
                                        .addComponent(a52))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a69)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a70)
                                        .addGap(18, 18, 18)
                                        .addComponent(a71)
                                        .addGap(18, 18, 18)
                                        .addComponent(a72))
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a73)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a74)
                                        .addGap(18, 18, 18)
                                        .addComponent(a75)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a76))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(a77)
                                        .addGap(45, 45, 45)
                                        .addComponent(a78)
                                        .addGap(44, 44, 44)
                                        .addComponent(a79)
                                        .addGap(37, 37, 37)
                                        .addComponent(a80))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(a61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a64))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a53)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a54)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a55)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a56))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a46)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a48))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(301, 301, 301)
                                .addComponent(a57)
                                .addGap(18, 18, 18)
                                .addComponent(a58)
                                .addGap(30, 30, 30)
                                .addComponent(a59)
                                .addGap(18, 18, 18)
                                .addComponent(a60))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a44)
                            .addComponent(a43)
                            .addComponent(a42)
                            .addComponent(a41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a2)
                            .addComponent(a3)
                            .addComponent(a4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a46)
                            .addComponent(a47)
                            .addComponent(a48))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a49, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a50)
                            .addComponent(a51)
                            .addComponent(a52)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a6)
                            .addComponent(a7)
                            .addComponent(a8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a10)
                            .addComponent(a11)
                            .addComponent(a12))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a57, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a58)
                            .addComponent(a59)
                            .addComponent(a60))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(a21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a22)
                            .addComponent(a23)
                            .addComponent(a24)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a53, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a54)
                                    .addComponent(a55)
                                    .addComponent(a56))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(a20))
                                .addGap(13, 13, 13))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(a15)
                                            .addComponent(a14)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(a16)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a18)
                                    .addComponent(a17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a19))))
                        .addComponent(jLabel6)
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a64)
                                    .addComponent(a63)
                                    .addComponent(a62)
                                    .addComponent(a61, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a26)
                            .addComponent(a27)
                            .addComponent(a28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a30)
                            .addComponent(a31)
                            .addComponent(a32)
                            .addComponent(jLabel18))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a33)
                                    .addComponent(a34)
                                    .addComponent(a35)
                                    .addComponent(a36)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(a69, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a70)
                                .addComponent(a71)
                                .addComponent(a72))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a68)
                            .addComponent(a67)
                            .addComponent(a66)
                            .addComponent(a65, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a37)
                            .addComponent(a39)
                            .addComponent(a40)
                            .addComponent(a38))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a73)
                            .addComponent(a75)
                            .addComponent(a76)
                            .addComponent(a74))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a77)
                            .addComponent(a78)
                            .addComponent(a79)
                            .addComponent(a80)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int b1=0,b2=0,b3=0,b4=0,b5=0,b6=0,b7=0,b8=0,b9=0,b10=0,b11=0,b12=0,b13=0,b14=0,b15=0,b16=0,b17=0,b18=0,b19=0,b20=0;

        int correct=0,incorrect=0,not=0;

        if(a1.isSelected()){

            b1=-1;

            incorrect++;

        }

        else if(a2.isSelected()){

            b1=-1;

            incorrect++;

        }

        else if(a3.isSelected()){

            b1=2;

            correct++;

        }

        else if(a4.isSelected()){

            b1=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a5.isSelected()){

            b2=-1;

            incorrect++;

        }

        else if(a6.isSelected()){

            b2=-1;

            incorrect++;

        }

        else if(a7.isSelected()){

            b2=-1;

            incorrect++;

        }

        else if(a8.isSelected()){

            b2=2;

            correct++;

        }

        else{

            not++;

        }

        if(a9.isSelected()){

            b3=-1;

            incorrect++;

        }

        else if(a10.isSelected()){

            b3=2;

            correct++;

        }

        else  if(a11.isSelected()){

            b3=-1;

            incorrect++;

        }

        else  if(a12.isSelected()){

            b3=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a13.isSelected()){

            b4=2;

            correct++;

        }

        else if(a14.isSelected()){

            b4=-1;

            incorrect++;

        }

        else  if(a15.isSelected()){

            b4=-1;

            incorrect++;

        }

        else  if(a16.isSelected()){

            b4=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a17.isSelected()){

            b5=-1;

            incorrect++;

        }

        else  if(a18.isSelected()){

            b5=-1;

            incorrect++;

        }

        else  if(a19.isSelected()){

            b5=2;

            correct++;

        }

        else  if(a20.isSelected()){

            b5=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a21.isSelected()){

            b6=-1;

            incorrect++;

        }

        else if(a22.isSelected()){

            b6=-1;

            incorrect++;

        }

        else if(a23.isSelected()){

            b6=2;

            correct++;

        }

        else if(a24.isSelected()){

            b6=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a25.isSelected()){

            b7=-1;

            incorrect++;

        }

        else if(a26.isSelected()){

            b7=-1;

            incorrect++;

        }

        else if(a27.isSelected()){

            b7=-1;

            incorrect++;

        }

        else if(a28.isSelected()){

            b7=2;

            correct++;

        }

        else{

            not++;

        }

        if(a29.isSelected()){

            b8=-1;

            incorrect++;

        }

        else if(a30.isSelected()){

            b8=2;

            correct++;

        }

        else  if(a31.isSelected()){

            b8=-1;

            incorrect++;

        }

        else  if(a32.isSelected()){

            b8=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a33.isSelected()){

            b9=2;
            correct++;

        }

        else if(a34.isSelected()){

            b9=-1;

            incorrect++;

        }

        else  if(a35.isSelected()){

            b9=-1;

            incorrect++;

        }

        else  if(a36.isSelected()){

            b9=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a37.isSelected()){

            b10=-1;

            incorrect++;

        }

        else  if(a38.isSelected()){

            b10=-1;

            incorrect++;

        }

        else  if(a39.isSelected()){

            b10=2;

            correct++;

        }

        else  if(a40.isSelected()){

            b10=-1;

            incorrect++;

        }

        else{

            not++;

        }
        if(a41.isSelected()){

            b11=-1;

            incorrect++;

        }

        else if(a42.isSelected()){

            b11=-1;

            incorrect++;

        }

        else if(a43.isSelected()){

            b11=2;

            correct++;

        }

        else if(a44.isSelected()){

            b11=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a45.isSelected()){

            b12=-1;

            incorrect++;

        }

        else if(a46.isSelected()){

            b12=-1;

            incorrect++;

        }

        else if(a47.isSelected()){

            b12=-1;

            incorrect++;

        }

        else if(a48.isSelected()){

            b12=2;

            correct++;

        }

        else{

            not++;

        }

        if(a49.isSelected()){

            b13=-1;

            incorrect++;

        }

        else if(a50.isSelected()){

            b13=2;

            correct++;

        }

        else  if(a51.isSelected()){

            b13=-1;

            incorrect++;

        }

        else  if(a52.isSelected()){

            b13=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a53.isSelected()){

            b14=2;

            correct++;

        }

        else if(a54.isSelected()){

            b14=-1;

            incorrect++;

        }

        else  if(a55.isSelected()){

            b14=-1;

            incorrect++;

        }

        else  if(a56.isSelected()){

            b14=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a57.isSelected()){

            b15=-1;

            incorrect++;

        }

        else  if(a58.isSelected()){

            b15=-1;

            incorrect++;

        }

        else  if(a59.isSelected()){

            b15=2;

            correct++;

        }

        else  if(a60.isSelected()){

            b15=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a61.isSelected()){

            b16=-1;

            incorrect++;

        }

        else if(a62.isSelected()){

            b16=-1;

            incorrect++;

        }

        else if(a63.isSelected()){

            b16=2;

            correct++;

        }

        else if(a64.isSelected()){

            b16=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a65.isSelected()){

            b17=-1;

            incorrect++;

        }

        else if(a66.isSelected()){

            b17=-1;

            incorrect++;

        }

        else if(a67.isSelected()){

            b17=-1;

            incorrect++;

        }

        else if(a68.isSelected()){

            b17=2;

            correct++;

        }

        else{

            not++;

        }

        if(a69.isSelected()){

            b18=-1;

            incorrect++;

        }

        else if(a70.isSelected()){

            b18=2;

            correct++;

        }

        else  if(a71.isSelected()){

            b18=-1;

            incorrect++;

        }

        else  if(a72.isSelected()){

            b18=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a73.isSelected()){

            b19=2;

            correct++;

        }

        else if(a74.isSelected()){

            b19=-1;

            incorrect++;

        }

        else  if(a75.isSelected()){

            b19=-1;

            incorrect++;

        }

        else  if(a76.isSelected()){

            b19=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a77.isSelected()){

            b20=-1;

            incorrect++;

        }

        else  if(a78.isSelected()){

            b20=-1;

            incorrect++;

        }

        else  if(a79.isSelected()){

            b20=2;

            correct++;

        }

        else  if(a80.isSelected()){

            b20=-1;

            incorrect++;

        }

        else{

            not++;

        }
        int Total=b1+b2+b3+b4+b5+b6+b7+b8+b9+b10+b11+b12+b13+b14+b15+b16+b17+b18+b19+b20;
        ResultScreen q1=new ResultScreen();
        q1.setValueInTextField(Total,correct,incorrect,not);
        q1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void a30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a30ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a10;
    private javax.swing.JRadioButton a11;
    private javax.swing.JRadioButton a12;
    private javax.swing.JRadioButton a13;
    private javax.swing.JRadioButton a14;
    private javax.swing.JRadioButton a15;
    private javax.swing.JRadioButton a16;
    private javax.swing.JRadioButton a17;
    private javax.swing.JRadioButton a18;
    private javax.swing.JRadioButton a19;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a20;
    private javax.swing.JRadioButton a21;
    private javax.swing.JRadioButton a22;
    private javax.swing.JRadioButton a23;
    private javax.swing.JRadioButton a24;
    private javax.swing.JRadioButton a25;
    private javax.swing.JRadioButton a26;
    private javax.swing.JRadioButton a27;
    private javax.swing.JRadioButton a28;
    private javax.swing.JRadioButton a29;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a30;
    private javax.swing.JRadioButton a31;
    private javax.swing.JRadioButton a32;
    private javax.swing.JRadioButton a33;
    private javax.swing.JRadioButton a34;
    private javax.swing.JRadioButton a35;
    private javax.swing.JRadioButton a36;
    private javax.swing.JRadioButton a37;
    private javax.swing.JRadioButton a38;
    private javax.swing.JRadioButton a39;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a40;
    private javax.swing.JRadioButton a41;
    private javax.swing.JRadioButton a42;
    private javax.swing.JRadioButton a43;
    private javax.swing.JRadioButton a44;
    private javax.swing.JRadioButton a45;
    private javax.swing.JRadioButton a46;
    private javax.swing.JRadioButton a47;
    private javax.swing.JRadioButton a48;
    private javax.swing.JRadioButton a49;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton a50;
    private javax.swing.JRadioButton a51;
    private javax.swing.JRadioButton a52;
    private javax.swing.JRadioButton a53;
    private javax.swing.JRadioButton a54;
    private javax.swing.JRadioButton a55;
    private javax.swing.JRadioButton a56;
    private javax.swing.JRadioButton a57;
    private javax.swing.JRadioButton a58;
    private javax.swing.JRadioButton a59;
    private javax.swing.JRadioButton a6;
    private javax.swing.JRadioButton a60;
    private javax.swing.JRadioButton a61;
    private javax.swing.JRadioButton a62;
    private javax.swing.JRadioButton a63;
    private javax.swing.JRadioButton a64;
    private javax.swing.JRadioButton a65;
    private javax.swing.JRadioButton a66;
    private javax.swing.JRadioButton a67;
    private javax.swing.JRadioButton a68;
    private javax.swing.JRadioButton a69;
    private javax.swing.JRadioButton a7;
    private javax.swing.JRadioButton a70;
    private javax.swing.JRadioButton a71;
    private javax.swing.JRadioButton a72;
    private javax.swing.JRadioButton a73;
    private javax.swing.JRadioButton a74;
    private javax.swing.JRadioButton a75;
    private javax.swing.JRadioButton a76;
    private javax.swing.JRadioButton a77;
    private javax.swing.JRadioButton a78;
    private javax.swing.JRadioButton a79;
    private javax.swing.JRadioButton a8;
    private javax.swing.JRadioButton a80;
    private javax.swing.JRadioButton a9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
