/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;

import java.awt.Color;

/**
 *
 * @author hp
 */
public class Question3 extends javax.swing.JFrame {

    /**
     * Creates new form Question3
     */
    public Question3() {
        initComponents();
          this.getContentPane().setBackground(Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        a1 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        a4 = new javax.swing.JRadioButton();
        a5 = new javax.swing.JRadioButton();
        a6 = new javax.swing.JRadioButton();
        a7 = new javax.swing.JRadioButton();
        a8 = new javax.swing.JRadioButton();
        a9 = new javax.swing.JRadioButton();
        a10 = new javax.swing.JRadioButton();
        a11 = new javax.swing.JRadioButton();
        a12 = new javax.swing.JRadioButton();
        a13 = new javax.swing.JRadioButton();
        a14 = new javax.swing.JRadioButton();
        a15 = new javax.swing.JRadioButton();
        a16 = new javax.swing.JRadioButton();
        a17 = new javax.swing.JRadioButton();
        a18 = new javax.swing.JRadioButton();
        a19 = new javax.swing.JRadioButton();
        a20 = new javax.swing.JRadioButton();
        a21 = new javax.swing.JRadioButton();
        a22 = new javax.swing.JRadioButton();
        a23 = new javax.swing.JRadioButton();
        a24 = new javax.swing.JRadioButton();
        a25 = new javax.swing.JRadioButton();
        a26 = new javax.swing.JRadioButton();
        a27 = new javax.swing.JRadioButton();
        a28 = new javax.swing.JRadioButton();
        a29 = new javax.swing.JRadioButton();
        a30 = new javax.swing.JRadioButton();
        a31 = new javax.swing.JRadioButton();
        a32 = new javax.swing.JRadioButton();
        a41 = new javax.swing.JRadioButton();
        a42 = new javax.swing.JRadioButton();
        a43 = new javax.swing.JRadioButton();
        a44 = new javax.swing.JRadioButton();
        a45 = new javax.swing.JRadioButton();
        a46 = new javax.swing.JRadioButton();
        a47 = new javax.swing.JRadioButton();
        a48 = new javax.swing.JRadioButton();
        a49 = new javax.swing.JRadioButton();
        a50 = new javax.swing.JRadioButton();
        a51 = new javax.swing.JRadioButton();
        a52 = new javax.swing.JRadioButton();
        a53 = new javax.swing.JRadioButton();
        a54 = new javax.swing.JRadioButton();
        a55 = new javax.swing.JRadioButton();
        a56 = new javax.swing.JRadioButton();
        a57 = new javax.swing.JRadioButton();
        a58 = new javax.swing.JRadioButton();
        a59 = new javax.swing.JRadioButton();
        a60 = new javax.swing.JRadioButton();
        a61 = new javax.swing.JRadioButton();
        a62 = new javax.swing.JRadioButton();
        a63 = new javax.swing.JRadioButton();
        a64 = new javax.swing.JRadioButton();
        a65 = new javax.swing.JRadioButton();
        a66 = new javax.swing.JRadioButton();
        a67 = new javax.swing.JRadioButton();
        a68 = new javax.swing.JRadioButton();
        a69 = new javax.swing.JRadioButton();
        a70 = new javax.swing.JRadioButton();
        a71 = new javax.swing.JRadioButton();
        a72 = new javax.swing.JRadioButton();
        a33 = new javax.swing.JRadioButton();
        a34 = new javax.swing.JRadioButton();
        a35 = new javax.swing.JRadioButton();
        a36 = new javax.swing.JRadioButton();
        a37 = new javax.swing.JRadioButton();
        a38 = new javax.swing.JRadioButton();
        a39 = new javax.swing.JRadioButton();
        a40 = new javax.swing.JRadioButton();
        a73 = new javax.swing.JRadioButton();
        a74 = new javax.swing.JRadioButton();
        a75 = new javax.swing.JRadioButton();
        a76 = new javax.swing.JRadioButton();
        a77 = new javax.swing.JRadioButton();
        a78 = new javax.swing.JRadioButton();
        a79 = new javax.swing.JRadioButton();
        a80 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(a1);
        a1.setLabel("JRE");
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 20));

        buttonGroup1.add(a2);
        a2.setLabel("JIT");
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        buttonGroup1.add(a3);
        a3.setActionCommand("JDK");
        a3.setLabel("JDK");
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        buttonGroup1.add(a4);
        a4.setActionCommand("JVM");
        a4.setLabel("JVM");
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        buttonGroup2.add(a5);
        a5.setText("object-oriented");
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        buttonGroup2.add(a6);
        a6.setText("Dynamic &Extensible");
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        buttonGroup2.add(a7);
        a7.setLabel("portable");
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        buttonGroup2.add(a8);
        a8.setText("Pointers");
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        buttonGroup3.add(a9);
        a9.setText("identifier & keyword");
        getContentPane().add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        buttonGroup3.add(a10);
        a10.setText("Keyword");
        getContentPane().add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        buttonGroup3.add(a11);
        a11.setText("identifier");
        a11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a11ActionPerformed(evt);
            }
        });
        getContentPane().add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        buttonGroup3.add(a12);
        a12.setText("none");
        getContentPane().add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        buttonGroup4.add(a13);
        a13.setText(".java");
        getContentPane().add(a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        buttonGroup4.add(a14);
        a14.setText(".js");
        getContentPane().add(a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        buttonGroup4.add(a15);
        a15.setText(".class");
        getContentPane().add(a15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        buttonGroup4.add(a16);
        a16.setText(".txt");
        getContentPane().add(a16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        buttonGroup5.add(a17);
        a17.setText(" Polymorphism");
        getContentPane().add(a17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        buttonGroup5.add(a18);
        a18.setText("Encapsulation");
        getContentPane().add(a18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        buttonGroup5.add(a19);
        a19.setText("Compilation");
        getContentPane().add(a19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        buttonGroup5.add(a20);
        a20.setText("Inheritance");
        getContentPane().add(a20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        buttonGroup6.add(a21);
        a21.setText(".txt");
        getContentPane().add(a21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 20));

        buttonGroup6.add(a22);
        a22.setText(".js");
        getContentPane().add(a22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        buttonGroup6.add(a23);
        a23.setText(".class");
        getContentPane().add(a23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        buttonGroup6.add(a24);
        a24.setText(".java");
        getContentPane().add(a24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        buttonGroup7.add(a25);
        a25.setText("break");
        getContentPane().add(a25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, 20));

        buttonGroup7.add(a26);
        a26.setText("continue");
        getContentPane().add(a26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        buttonGroup7.add(a27);
        a27.setText("for()");
        getContentPane().add(a27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        buttonGroup7.add(a28);
        a28.setText("if()");
        getContentPane().add(a28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, -1));

        buttonGroup8.add(a29);
        a29.setText("intf");
        getContentPane().add(a29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, 20));

        buttonGroup8.add(a30);
        a30.setText("interface");
        getContentPane().add(a30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, -1, -1));

        buttonGroup8.add(a31);
        a31.setText("Intf");
        a31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a31ActionPerformed(evt);
            }
        });
        getContentPane().add(a31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        buttonGroup8.add(a32);
        a32.setText("Interface");
        getContentPane().add(a32, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, -1, -1));

        buttonGroup11.add(a41);
        a41.setText("jRadioButton1");
        getContentPane().add(a41, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, 20));

        buttonGroup11.add(a42);
        a42.setText("jRadioButton1");
        getContentPane().add(a42, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, -1, -1));

        buttonGroup11.add(a43);
        a43.setText("jRadioButton1");
        getContentPane().add(a43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, -1, -1));

        buttonGroup11.add(a44);
        a44.setText("jRadioButton1");
        getContentPane().add(a44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 50, -1, -1));

        buttonGroup12.add(a45);
        a45.setText("jRadioButton1");
        getContentPane().add(a45, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, -1, 20));

        buttonGroup12.add(a46);
        a46.setText("jRadioButton1");
        getContentPane().add(a46, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, -1, -1));

        buttonGroup12.add(a47);
        a47.setText("jRadioButton1");
        getContentPane().add(a47, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 120, -1, -1));

        buttonGroup12.add(a48);
        a48.setText("jRadioButton1");
        getContentPane().add(a48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 120, -1, -1));

        buttonGroup13.add(a49);
        a49.setText("jRadioButton1");
        getContentPane().add(a49, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, 20));

        buttonGroup13.add(a50);
        a50.setText("jRadioButton1");
        getContentPane().add(a50, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, -1, -1));

        buttonGroup13.add(a51);
        a51.setText("jRadioButton1");
        getContentPane().add(a51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 200, -1, -1));

        buttonGroup13.add(a52);
        a52.setText("jRadioButton1");
        getContentPane().add(a52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 200, -1, -1));

        buttonGroup14.add(a53);
        a53.setText("jRadioButton1");
        getContentPane().add(a53, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, 20));

        buttonGroup14.add(a54);
        a54.setText("jRadioButton1");
        getContentPane().add(a54, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, -1, -1));

        buttonGroup14.add(a55);
        a55.setText("jRadioButton1");
        getContentPane().add(a55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, -1, -1));

        buttonGroup14.add(a56);
        a56.setText("jRadioButton1");
        getContentPane().add(a56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 270, -1, -1));

        buttonGroup15.add(a57);
        a57.setText("jRadioButton1");
        getContentPane().add(a57, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 20));

        buttonGroup15.add(a58);
        a58.setText("jRadioButton1");
        getContentPane().add(a58, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, -1, -1));

        buttonGroup15.add(a59);
        a59.setText("jRadioButton1");
        getContentPane().add(a59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 340, -1, -1));

        buttonGroup15.add(a60);
        a60.setText("jRadioButton1");
        getContentPane().add(a60, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 340, -1, -1));

        buttonGroup16.add(a61);
        a61.setText("jRadioButton1");
        getContentPane().add(a61, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, -1, 20));

        buttonGroup16.add(a62);
        a62.setText("jRadioButton1");
        getContentPane().add(a62, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, -1, -1));

        buttonGroup16.add(a63);
        a63.setText("jRadioButton1");
        getContentPane().add(a63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 410, -1, -1));

        buttonGroup16.add(a64);
        a64.setText("jRadioButton1");
        getContentPane().add(a64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 410, -1, -1));

        buttonGroup17.add(a65);
        a65.setText("jRadioButton1");
        getContentPane().add(a65, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, -1, 20));

        buttonGroup17.add(a66);
        a66.setText("jRadioButton1");
        getContentPane().add(a66, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, -1, -1));

        buttonGroup17.add(a67);
        a67.setText("jRadioButton1");
        getContentPane().add(a67, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 490, -1, -1));

        buttonGroup17.add(a68);
        a68.setText("jRadioButton1");
        getContentPane().add(a68, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 490, -1, -1));

        buttonGroup18.add(a69);
        a69.setText("jRadioButton1");
        getContentPane().add(a69, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, -1, 20));

        buttonGroup18.add(a70);
        a70.setText("jRadioButton1");
        getContentPane().add(a70, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 560, -1, -1));

        buttonGroup18.add(a71);
        a71.setText("jRadioButton1");
        getContentPane().add(a71, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 560, -1, -1));

        buttonGroup18.add(a72);
        a72.setText("jRadioButton1");
        getContentPane().add(a72, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 560, -1, -1));

        buttonGroup9.add(a33);
        a33.setText("Object class");
        getContentPane().add(a33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, 20));

        buttonGroup9.add(a34);
        a34.setText("ArrayList");
        getContentPane().add(a34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, -1, -1));

        buttonGroup9.add(a35);
        a35.setText("Abstract class");
        getContentPane().add(a35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, -1, -1));

        buttonGroup9.add(a36);
        a36.setText("String");
        getContentPane().add(a36, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, -1, -1));

        buttonGroup10.add(a37);
        a37.setText("JProfiler");
        getContentPane().add(a37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, -1, 20));

        buttonGroup10.add(a38);
        a38.setText("Eclipse Profiler");
        getContentPane().add(a38, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, -1, -1));

        buttonGroup10.add(a39);
        a39.setText("JVM");
        getContentPane().add(a39, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, -1, -1));

        buttonGroup10.add(a40);
        a40.setText(" JConsole");
        getContentPane().add(a40, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 680, -1, -1));

        buttonGroup19.add(a73);
        a73.setText("jRadioButton1");
        getContentPane().add(a73, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 610, -1, 20));

        buttonGroup19.add(a74);
        a74.setText("jRadioButton1");
        getContentPane().add(a74, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 610, -1, -1));

        buttonGroup19.add(a75);
        a75.setText("jRadioButton1");
        getContentPane().add(a75, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, -1, -1));

        buttonGroup19.add(a76);
        a76.setText("jRadioButton1");
        getContentPane().add(a76, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 610, -1, -1));

        buttonGroup20.add(a77);
        a77.setText("jRadioButton1");
        getContentPane().add(a77, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, -1, 20));

        buttonGroup20.add(a78);
        a78.setText("jRadioButton1");
        getContentPane().add(a78, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 680, -1, -1));

        buttonGroup20.add(a79);
        a79.setText("jRadioButton1");
        getContentPane().add(a79, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 680, -1, -1));

        buttonGroup20.add(a80);
        a80.setText("jRadioButton1");
        getContentPane().add(a80, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 680, -1, -1));

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 110, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("2.which one of the following is not a java feature?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("10.Which of the below is not a Java Profiler?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 650, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("3.Which of these can't be used for a variable name in java?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("4.What is the extension of java code files?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("5.Which of the following is not an OOPS concept in Java?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("6.What is the extension of compiled java classes?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("7.Which of these are selection statements in Java?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("8.Which of these keywords is used to define interfaces in Java?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("9.Which of the following is a superclass of every class in Java?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("1. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("JAVA QUESTIONS");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 220, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int b1=0,b2=0,b3=0,b4=0,b5=0,b6=0,b7=0,b8=0,b9=0,b10=0,b11=0,b12=0,b13=0,b14=0,b15=0,b16=0,b17=0,b18=0,b19=0,b20=0;

        int correct=0,incorrect=0,not=0;

        if(a1.isSelected()){

            b1=-1;

            incorrect++;

        }

        else if(a2.isSelected()){

            b1=-1;

            incorrect++;

        }

        else if(a3.isSelected()){

            b1=2;

            correct++;

        }

        else if(a4.isSelected()){

            b1=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a5.isSelected()){

            b2=-1;

            incorrect++;

        }

        else if(a6.isSelected()){

            b2=-1;

            incorrect++;

        }

        else if(a7.isSelected()){

            b2=-1;

            incorrect++;

        }

        else if(a8.isSelected()){

            b2=2;

            correct++;

        }

        else{

            not++;

        }

        if(a9.isSelected()){

            b3=-1;

            incorrect++;

        }

        else if(a10.isSelected()){

            b3=2;

            correct++;

        }

        else  if(a11.isSelected()){

            b3=-1;

            incorrect++;

        }

        else  if(a12.isSelected()){

            b3=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a13.isSelected()){

            b4=2;

            correct++;

        }

        else if(a14.isSelected()){

            b4=-1;

            incorrect++;

        }

        else  if(a15.isSelected()){

            b4=-1;

            incorrect++;

        }

        else  if(a16.isSelected()){

            b4=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a17.isSelected()){

            b5=-1;

            incorrect++;

        }

        else  if(a18.isSelected()){

            b5=-1;

            incorrect++;

        }

        else  if(a19.isSelected()){

            b5=2;

            correct++;

        }

        else  if(a20.isSelected()){

            b5=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a21.isSelected()){

            b6=-1;

            incorrect++;

        }

        else if(a22.isSelected()){

            b6=-1;

            incorrect++;

        }

        else if(a23.isSelected()){

            b6=2;

            correct++;

        }

        else if(a24.isSelected()){

            b6=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a25.isSelected()){

            b7=-1;

            incorrect++;

        }

        else if(a26.isSelected()){

            b7=-1;

            incorrect++;

        }

        else if(a27.isSelected()){

            b7=-1;

            incorrect++;

        }

        else if(a28.isSelected()){

            b7=2;

            correct++;

        }

        else{

            not++;

        }

        if(a29.isSelected()){

            b8=-1;

            incorrect++;

        }

        else if(a30.isSelected()){

            b8=2;

            correct++;

        }

        else  if(a31.isSelected()){

            b8=-1;

            incorrect++;

        }

        else  if(a32.isSelected()){

            b8=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a33.isSelected()){

            b9=2;
            correct++;

        }

        else if(a34.isSelected()){

            b9=-1;

            incorrect++;

        }

        else  if(a35.isSelected()){

            b9=-1;

            incorrect++;

        }

        else  if(a36.isSelected()){

            b9=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a37.isSelected()){

            b10=-1;

            incorrect++;

        }

        else  if(a38.isSelected()){

            b10=-1;

            incorrect++;

        }

        else  if(a39.isSelected()){

            b10=2;

            correct++;

        }

        else  if(a40.isSelected()){

            b10=-1;

            incorrect++;

        }

        else{

            not++;

        }
        if(a41.isSelected()){

            b11=-1;

            incorrect++;

        }

        else if(a42.isSelected()){

            b11=-1;

            incorrect++;

        }

        else if(a43.isSelected()){

            b11=2;

            correct++;

        }

        else if(a44.isSelected()){

            b11=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a45.isSelected()){

            b12=-1;

            incorrect++;

        }

        else if(a46.isSelected()){

            b12=-1;

            incorrect++;

        }

        else if(a47.isSelected()){

            b12=-1;

            incorrect++;

        }

        else if(a48.isSelected()){

            b12=2;

            correct++;

        }

        else{

            not++;

        }

        if(a49.isSelected()){

            b13=-1;

            incorrect++;

        }

        else if(a50.isSelected()){

            b13=2;

            correct++;

        }

        else  if(a51.isSelected()){

            b13=-1;

            incorrect++;

        }

        else  if(a52.isSelected()){

            b13=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a53.isSelected()){

            b14=2;

            correct++;

        }

        else if(a54.isSelected()){

            b14=-1;

            incorrect++;

        }

        else  if(a55.isSelected()){

            b14=-1;

            incorrect++;

        }

        else  if(a56.isSelected()){

            b14=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a57.isSelected()){

            b15=-1;

            incorrect++;

        }

        else  if(a58.isSelected()){

            b15=-1;

            incorrect++;

        }

        else  if(a59.isSelected()){

            b15=2;

            correct++;

        }

        else  if(a60.isSelected()){

            b15=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a61.isSelected()){

            b16=-1;

            incorrect++;

        }

        else if(a62.isSelected()){

            b16=-1;

            incorrect++;

        }

        else if(a63.isSelected()){

            b16=2;

            correct++;

        }

        else if(a64.isSelected()){

            b16=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a65.isSelected()){

            b17=-1;

            incorrect++;

        }

        else if(a66.isSelected()){

            b17=-1;

            incorrect++;

        }

        else if(a67.isSelected()){

            b17=-1;

            incorrect++;

        }

        else if(a68.isSelected()){

            b17=2;

            correct++;

        }

        else{

            not++;

        }

        if(a69.isSelected()){

            b18=-1;

            incorrect++;

        }

        else if(a70.isSelected()){

            b18=2;

            correct++;

        }

        else  if(a71.isSelected()){

            b18=-1;

            incorrect++;

        }

        else  if(a72.isSelected()){

            b18=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a73.isSelected()){

            b19=2;

            correct++;

        }

        else if(a74.isSelected()){

            b19=-1;

            incorrect++;

        }

        else  if(a75.isSelected()){

            b19=-1;

            incorrect++;

        }

        else  if(a76.isSelected()){

            b19=-1;

            incorrect++;

        }

        else{

            not++;

        }

        if(a77.isSelected()){

            b20=-1;

            incorrect++;

        }

        else  if(a78.isSelected()){

            b20=-1;

            incorrect++;

        }

        else  if(a79.isSelected()){

            b20=2;

            correct++;

        }

        else  if(a80.isSelected()){

            b20=-1;

            incorrect++;

        }

        else{

            not++;

        }
        int Total=b1+b2+b3+b4+b5+b6+b7+b8+b9+b10+b11+b12+b13+b14+b15+b16+b17+b18+b19+b20;
        ResultScreen q1=new ResultScreen();
        q1.setValueInTextField(Total,correct,incorrect,not);
        q1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a7ActionPerformed

    private void a11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a11ActionPerformed

    private void a31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a31ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a10;
    private javax.swing.JRadioButton a11;
    private javax.swing.JRadioButton a12;
    private javax.swing.JRadioButton a13;
    private javax.swing.JRadioButton a14;
    private javax.swing.JRadioButton a15;
    private javax.swing.JRadioButton a16;
    private javax.swing.JRadioButton a17;
    private javax.swing.JRadioButton a18;
    private javax.swing.JRadioButton a19;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a20;
    private javax.swing.JRadioButton a21;
    private javax.swing.JRadioButton a22;
    private javax.swing.JRadioButton a23;
    private javax.swing.JRadioButton a24;
    private javax.swing.JRadioButton a25;
    private javax.swing.JRadioButton a26;
    private javax.swing.JRadioButton a27;
    private javax.swing.JRadioButton a28;
    private javax.swing.JRadioButton a29;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a30;
    private javax.swing.JRadioButton a31;
    private javax.swing.JRadioButton a32;
    private javax.swing.JRadioButton a33;
    private javax.swing.JRadioButton a34;
    private javax.swing.JRadioButton a35;
    private javax.swing.JRadioButton a36;
    private javax.swing.JRadioButton a37;
    private javax.swing.JRadioButton a38;
    private javax.swing.JRadioButton a39;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a40;
    private javax.swing.JRadioButton a41;
    private javax.swing.JRadioButton a42;
    private javax.swing.JRadioButton a43;
    private javax.swing.JRadioButton a44;
    private javax.swing.JRadioButton a45;
    private javax.swing.JRadioButton a46;
    private javax.swing.JRadioButton a47;
    private javax.swing.JRadioButton a48;
    private javax.swing.JRadioButton a49;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton a50;
    private javax.swing.JRadioButton a51;
    private javax.swing.JRadioButton a52;
    private javax.swing.JRadioButton a53;
    private javax.swing.JRadioButton a54;
    private javax.swing.JRadioButton a55;
    private javax.swing.JRadioButton a56;
    private javax.swing.JRadioButton a57;
    private javax.swing.JRadioButton a58;
    private javax.swing.JRadioButton a59;
    private javax.swing.JRadioButton a6;
    private javax.swing.JRadioButton a60;
    private javax.swing.JRadioButton a61;
    private javax.swing.JRadioButton a62;
    private javax.swing.JRadioButton a63;
    private javax.swing.JRadioButton a64;
    private javax.swing.JRadioButton a65;
    private javax.swing.JRadioButton a66;
    private javax.swing.JRadioButton a67;
    private javax.swing.JRadioButton a68;
    private javax.swing.JRadioButton a69;
    private javax.swing.JRadioButton a7;
    private javax.swing.JRadioButton a70;
    private javax.swing.JRadioButton a71;
    private javax.swing.JRadioButton a72;
    private javax.swing.JRadioButton a73;
    private javax.swing.JRadioButton a74;
    private javax.swing.JRadioButton a75;
    private javax.swing.JRadioButton a76;
    private javax.swing.JRadioButton a77;
    private javax.swing.JRadioButton a78;
    private javax.swing.JRadioButton a79;
    private javax.swing.JRadioButton a8;
    private javax.swing.JRadioButton a80;
    private javax.swing.JRadioButton a9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
