/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;

;
import java.awt.*;
import javax.swing.JFrame;

/**
 *
 * @author hp
 */
public class Question1 extends javax.swing.JFrame {
    
    /**
     * Creates new form Question1
     */
    public Question1() {
        initComponents();
        this.getContentPane().setBackground(Color.CYAN);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        jLabel26 = new javax.swing.JLabel();
        a1 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        a4 = new javax.swing.JRadioButton();
        a5 = new javax.swing.JRadioButton();
        a6 = new javax.swing.JRadioButton();
        a7 = new javax.swing.JRadioButton();
        a8 = new javax.swing.JRadioButton();
        a9 = new javax.swing.JRadioButton();
        a10 = new javax.swing.JRadioButton();
        a11 = new javax.swing.JRadioButton();
        a12 = new javax.swing.JRadioButton();
        a13 = new javax.swing.JRadioButton();
        a14 = new javax.swing.JRadioButton();
        a15 = new javax.swing.JRadioButton();
        a16 = new javax.swing.JRadioButton();
        a17 = new javax.swing.JRadioButton();
        a18 = new javax.swing.JRadioButton();
        a19 = new javax.swing.JRadioButton();
        a20 = new javax.swing.JRadioButton();
        a21 = new javax.swing.JRadioButton();
        a22 = new javax.swing.JRadioButton();
        a23 = new javax.swing.JRadioButton();
        a24 = new javax.swing.JRadioButton();
        a25 = new javax.swing.JRadioButton();
        a26 = new javax.swing.JRadioButton();
        a27 = new javax.swing.JRadioButton();
        a28 = new javax.swing.JRadioButton();
        a29 = new javax.swing.JRadioButton();
        a30 = new javax.swing.JRadioButton();
        a31 = new javax.swing.JRadioButton();
        a32 = new javax.swing.JRadioButton();
        a33 = new javax.swing.JRadioButton();
        a34 = new javax.swing.JRadioButton();
        a35 = new javax.swing.JRadioButton();
        a36 = new javax.swing.JRadioButton();
        a37 = new javax.swing.JRadioButton();
        a38 = new javax.swing.JRadioButton();
        a39 = new javax.swing.JRadioButton();
        a40 = new javax.swing.JRadioButton();
        a41 = new javax.swing.JRadioButton();
        a42 = new javax.swing.JRadioButton();
        a43 = new javax.swing.JRadioButton();
        a44 = new javax.swing.JRadioButton();
        a45 = new javax.swing.JRadioButton();
        a46 = new javax.swing.JRadioButton();
        a47 = new javax.swing.JRadioButton();
        a48 = new javax.swing.JRadioButton();
        a49 = new javax.swing.JRadioButton();
        a50 = new javax.swing.JRadioButton();
        a51 = new javax.swing.JRadioButton();
        a52 = new javax.swing.JRadioButton();
        a53 = new javax.swing.JRadioButton();
        a54 = new javax.swing.JRadioButton();
        a55 = new javax.swing.JRadioButton();
        a56 = new javax.swing.JRadioButton();
        a57 = new javax.swing.JRadioButton();
        a58 = new javax.swing.JRadioButton();
        a59 = new javax.swing.JRadioButton();
        a60 = new javax.swing.JRadioButton();
        a61 = new javax.swing.JRadioButton();
        a62 = new javax.swing.JRadioButton();
        a63 = new javax.swing.JRadioButton();
        a64 = new javax.swing.JRadioButton();
        a65 = new javax.swing.JRadioButton();
        a66 = new javax.swing.JRadioButton();
        a67 = new javax.swing.JRadioButton();
        a68 = new javax.swing.JRadioButton();
        a69 = new javax.swing.JRadioButton();
        a70 = new javax.swing.JRadioButton();
        a71 = new javax.swing.JRadioButton();
        a72 = new javax.swing.JRadioButton();
        a73 = new javax.swing.JRadioButton();
        a74 = new javax.swing.JRadioButton();
        a75 = new javax.swing.JRadioButton();
        a76 = new javax.swing.JRadioButton();
        a77 = new javax.swing.JRadioButton();
        a78 = new javax.swing.JRadioButton();
        a79 = new javax.swing.JRadioButton();
        a80 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        jLabel26.setText("jLabel26");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(a1);
        a1.setText("Guido van Rossum");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        buttonGroup1.add(a2);
        a2.setText("James Gosling");
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        buttonGroup1.add(a3);
        a3.setText("Dennis Ritchie");
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        buttonGroup1.add(a4);
        a4.setText("Bjarne Stroustrup");
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        buttonGroup2.add(a5);
        a5.setText(" JRE");
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        buttonGroup2.add(a6);
        a6.setText(" JIT");
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        buttonGroup2.add(a7);
        a7.setText("JDK");
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        buttonGroup2.add(a8);
        a8.setText(" JVM");
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        buttonGroup3.add(a9);
        a9.setText("Object-oriented");
        getContentPane().add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        buttonGroup3.add(a10);
        a10.setText("Use of pointers");
        getContentPane().add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        buttonGroup3.add(a11);
        a11.setText("Portable");
        getContentPane().add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        buttonGroup3.add(a12);
        a12.setText("Dynamic and Extensible");
        getContentPane().add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        buttonGroup4.add(a13);
        a13.setText(" .js");
        getContentPane().add(a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        buttonGroup4.add(a14);
        a14.setText(" .txt");
        getContentPane().add(a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        buttonGroup4.add(a15);
        a15.setText(" .class");
        getContentPane().add(a15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        buttonGroup4.add(a16);
        a16.setText(".java");
        getContentPane().add(a16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        buttonGroup5.add(a17);
        a17.setText("identifier & keyword");
        getContentPane().add(a17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 20));

        buttonGroup5.add(a18);
        a18.setText(" identifier");
        getContentPane().add(a18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        buttonGroup5.add(a19);
        a19.setText("keyword");
        getContentPane().add(a19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        buttonGroup5.add(a20);
        a20.setText("none of the mentioned");
        getContentPane().add(a20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        buttonGroup6.add(a21);
        a21.setText("Floating-point value assigned to a Floating type");
        getContentPane().add(a21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        buttonGroup6.add(a22);
        a22.setText("Floating-point value assigned to an integer type");
        getContentPane().add(a22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        buttonGroup6.add(a23);
        a23.setText("Integer value assigned to floating type");
        getContentPane().add(a23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        buttonGroup6.add(a24);
        a24.setText("Integer value assigned to floating type");
        getContentPane().add(a24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        buttonGroup7.add(a25);
        a25.setText("MemoryError");
        getContentPane().add(a25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, 20));

        buttonGroup7.add(a26);
        a26.setText("OutOfMemoryError");
        getContentPane().add(a26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        buttonGroup7.add(a27);
        a27.setText("MemoryOutOfBoundsException");
        getContentPane().add(a27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        buttonGroup7.add(a28);
        a28.setText("MemoryFullException");
        getContentPane().add(a28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        buttonGroup8.add(a29);
        a29.setText("ArrayList");
        getContentPane().add(a29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, 20));

        buttonGroup8.add(a30);
        a30.setText("Abstract class");
        getContentPane().add(a30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, -1, -1));

        buttonGroup8.add(a31);
        a31.setText("Object class");
        getContentPane().add(a31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        buttonGroup8.add(a32);
        a32.setText("String");
        getContentPane().add(a32, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));

        buttonGroup9.add(a33);
        a33.setText("127");
        getContentPane().add(a33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, 20));

        buttonGroup9.add(a34);
        a34.setText("126");
        getContentPane().add(a34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, -1, -1));

        buttonGroup9.add(a35);
        a35.setText(" Runtime Error");
        getContentPane().add(a35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, -1, -1));

        buttonGroup9.add(a36);
        a36.setText("Compilation Error");
        getContentPane().add(a36, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, -1, -1));

        buttonGroup10.add(a37);
        a37.setText("java.io");
        a37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a37ActionPerformed(evt);
            }
        });
        getContentPane().add(a37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, 20));

        buttonGroup10.add(a38);
        a38.setText("java.system");
        getContentPane().add(a38, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, -1, -1));

        buttonGroup10.add(a39);
        a39.setText("java.lang");
        getContentPane().add(a39, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, -1, -1));

        buttonGroup10.add(a40);
        a40.setText("java.util");
        getContentPane().add(a40, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 650, -1, -1));

        buttonGroup11.add(a41);
        a41.setText("check");
        getContentPane().add(a41, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, 20));

        buttonGroup11.add(a42);
        a42.setText("throw");
        getContentPane().add(a42, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        buttonGroup11.add(a43);
        a43.setText(" catch");
        getContentPane().add(a43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, -1, -1));

        buttonGroup11.add(a44);
        a44.setText("try");
        getContentPane().add(a44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, -1, -1));

        buttonGroup12.add(a45);
        a45.setText("0 to 256");
        getContentPane().add(a45, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, -1, 20));

        buttonGroup12.add(a46);
        a46.setText("-128 to 127");
        getContentPane().add(a46, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, -1, -1));

        buttonGroup12.add(a47);
        a47.setText("0 to 65535");
        getContentPane().add(a47, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 100, -1, -1));

        buttonGroup12.add(a48);
        a48.setText(" 0 to 32767");
        getContentPane().add(a48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 100, -1, -1));

        buttonGroup13.add(a49);
        a49.setText("Server");
        getContentPane().add(a49, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, 20));

        buttonGroup13.add(a50);
        a50.setText(" ServerReader");
        getContentPane().add(a50, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, -1, -1));

        buttonGroup13.add(a51);
        a51.setText("Socket");
        getContentPane().add(a51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, -1, -1));

        buttonGroup13.add(a52);
        a52.setText("ServerSocket");
        getContentPane().add(a52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 160, -1, -1));

        buttonGroup14.add(a53);
        a53.setText("super");
        getContentPane().add(a53, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, 20));

        buttonGroup14.add(a54);
        a54.setText("this");
        getContentPane().add(a54, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, -1, -1));

        buttonGroup14.add(a55);
        a55.setText("extent");
        getContentPane().add(a55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, -1, -1));

        buttonGroup14.add(a56);
        a56.setText("extends");
        getContentPane().add(a56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 230, -1, -1));

        buttonGroup15.add(a57);
        a57.setText("Method overloading");
        getContentPane().add(a57, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, 20));

        buttonGroup15.add(a58);
        a58.setText("Method overriding");
        getContentPane().add(a58, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 300, -1, -1));

        buttonGroup15.add(a59);
        a59.setText("Method hiding");
        getContentPane().add(a59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 300, -1, -1));

        buttonGroup15.add(a60);
        a60.setText("None of the mentioned");
        getContentPane().add(a60, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 300, -1, -1));

        buttonGroup16.add(a61);
        a61.setText("static");
        a61.setToolTipText("");
        getContentPane().add(a61, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, -1, 20));

        buttonGroup16.add(a62);
        a62.setText("constant");
        a62.setToolTipText("");
        getContentPane().add(a62, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, -1, -1));

        buttonGroup16.add(a63);
        a63.setText("protected");
        a63.setToolTipText("");
        getContentPane().add(a63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, -1, -1));

        buttonGroup16.add(a64);
        a64.setText("final");
        a64.setToolTipText("");
        getContentPane().add(a64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 360, -1, -1));

        buttonGroup17.add(a65);
        a65.setText("super(void);");
        a65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a65ActionPerformed(evt);
            }
        });
        getContentPane().add(a65, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, -1, 20));

        buttonGroup17.add(a66);
        a66.setText("superclass.();");
        getContentPane().add(a66, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 440, -1, -1));

        buttonGroup17.add(a67);
        a67.setText("super.A();");
        getContentPane().add(a67, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 440, -1, -1));

        buttonGroup17.add(a68);
        a68.setText("super();");
        getContentPane().add(a68, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 440, -1, -1));

        buttonGroup18.add(a69);
        a69.setText(" final, native, private");
        a69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a69ActionPerformed(evt);
            }
        });
        getContentPane().add(a69, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, -1, 20));

        buttonGroup18.add(a70);
        a70.setText("final, static, protected");
        getContentPane().add(a70, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 530, -1, -1));

        buttonGroup18.add(a71);
        a71.setText("final, private, abstract");
        getContentPane().add(a71, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 530, -1, -1));

        buttonGroup18.add(a72);
        a72.setText("final, static, public");
        a72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a72ActionPerformed(evt);
            }
        });
        getContentPane().add(a72, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 530, -1, -1));

        buttonGroup19.add(a73);
        a73.setText("Abstraction");
        getContentPane().add(a73, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, -1, 20));

        buttonGroup19.add(a74);
        a74.setText(" Encapsulation");
        getContentPane().add(a74, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 590, -1, -1));

        buttonGroup19.add(a75);
        a75.setText("Polymorphism");
        getContentPane().add(a75, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 590, -1, -1));

        buttonGroup19.add(a76);
        a76.setText("none of the above");
        getContentPane().add(a76, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 590, -1, -1));

        buttonGroup20.add(a77);
        a77.setText("java.io.date");
        getContentPane().add(a77, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, 20));

        buttonGroup20.add(a78);
        a78.setText(" java.sql.date");
        getContentPane().add(a78, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 650, -1, -1));

        buttonGroup20.add(a79);
        a79.setText("java.util.date");
        getContentPane().add(a79, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 650, -1, -1));

        buttonGroup20.add(a80);
        a80.setText("java.util.dateTime");
        getContentPane().add(a80, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 650, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 110, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("10.Which of these packages contains the exception Stack Overflow in Java?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("1.Who invented Java Programming?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("signature as a method in its superclass?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("3.Which one of the following is not a Java feature?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("4.What is the extension of java code files?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("5.Which of these cannot be used for a variable name in Java?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("6.What is Truncation in Java?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("7. Which exception is thrown when java is out of memory?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("8.Which of the following is a superclass of every class in Java?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("9.Host URL is having length of content 127.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("2. Which component is used to compile, debug and execute the java programs?");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("11.Which of these keywords are used for the block to be examined for exceptions?");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("12.What is the numerical range of a char data type in Java?");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("13.Which class provides system independent server side implementation?");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("of superclass?");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("14.Which of this keyword can be used in a subclass to call the constructor ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("parameters, of superclass A by subclass B?");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("15.What is the process of defining a method in a subclass having same name & type ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("16.Which of these keywords can be used to prevent Method overriding?");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("qualifiers among “final, static, native, public, private, abstract, ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("17.Which of these is correct way of calling a constructor having no ");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("20.Which of the following contains both date and time?");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, -1, -1));

        jLabel23.setText("public interface Status    {         /* insert qualifier here */ int MY_VALUE = 10;    }");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("18.At line number 2 in the following code, choose 3 valid data-type attributes/");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("19.Which of these is supported by method overriding in Java?");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 110, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("     JAVA QUESTIONS");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 280, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int b1=0,b2=0,b3=0,b4=0,b5=0,b6=0,b7=0,b8=0,b9=0,b10=0,b11=0,b12=0,b13=0,b14=0,b15=0,b16=0,b17=0,b18=0,b19=0,b20=0;
          
         int correct=0,incorrect=0,not=0;

        if(a1.isSelected()){

            b1=-1;

            incorrect++;

        }

       else if(a2.isSelected()){

            b1=-1;

            incorrect++;

        }

       else if(a3.isSelected()){

            b1=2;

            correct++;

        }

       else if(a4.isSelected()){

            b1=-1;

            incorrect++;

        }

       else{

           not++;

    

       }

        if(a5.isSelected()){

            b2=-1;

            incorrect++;

        }

       else if(a6.isSelected()){

            b2=-1;

            incorrect++;

        }

       else if(a7.isSelected()){

            b2=-1;

            incorrect++;

        }

       

               else if(a8.isSelected()){

            b2=2;

            correct++;

        }

               else{

                 not++;

             }

              if(a9.isSelected()){

            b3=-1;

            incorrect++;

        }

            

               else if(a10.isSelected()){

            b3=2;

            correct++;

        }

              else  if(a11.isSelected()){

            b3=-1;

            incorrect++;

        }

              else  if(a12.isSelected()){

                    b3=-1;

                    incorrect++;

                }

              else{

                 not++;

             }

                 if(a13.isSelected()){

                    b4=2;

                    correct++;

                }

                 else if(a14.isSelected()){

                    b4=-1;

                    incorrect++;

                }

                 else  if(a15.isSelected()){

                    b4=-1;

                    incorrect++;

                }

                  else  if(a16.isSelected()){

                    b4=-1;

                    incorrect++;

                }

                 else{

                 not++;

             }

                     if(a17.isSelected()){

                    b5=-1;

                    incorrect++;

                }

                    else  if(a18.isSelected()){

                    b5=-1;

                    incorrect++;

                }

                     else  if(a19.isSelected()){

                    b5=2;

                    correct++;

                }

                      else  if(a20.isSelected()){

                    b5=-1;

                    incorrect++;

                }
            
                     else{

                 not++;

             }
                     
        if(a21.isSelected()){

            b6=-1;

            incorrect++;

        }

       else if(a22.isSelected()){

            b6=-1;

            incorrect++;

        }

       else if(a23.isSelected()){

            b6=2;

            correct++;

        }

       else if(a24.isSelected()){

            b6=-1;

            incorrect++;

        }

       else{

           not++;

    

       }

        if(a25.isSelected()){

            b7=-1;

            incorrect++;

        }

       else if(a26.isSelected()){

            b7=-1;

            incorrect++;

        }

       else if(a27.isSelected()){

            b7=-1;

            incorrect++;

        }

       

               else if(a28.isSelected()){

            b7=2;

            correct++;

        }

               else{

                 not++;

             }

              if(a29.isSelected()){

            b8=-1;

            incorrect++;

        }

            

               else if(a30.isSelected()){

            b8=2;

            correct++;

        }

              else  if(a31.isSelected()){

            b8=-1;

            incorrect++;

        }

              else  if(a32.isSelected()){

                    b8=-1;

                    incorrect++;

                }

              else{

                 not++;

             }

                 if(a33.isSelected()){

                    b9=2;
                    correct++;

                }

                 else if(a34.isSelected()){

                    b9=-1;

                    incorrect++;

                }

                 else  if(a35.isSelected()){

                    b9=-1;

                    incorrect++;

                }

                  else  if(a36.isSelected()){

                    b9=-1;

                    incorrect++;

                }

                 else{

                 not++;

             }

                     if(a37.isSelected()){

                    b10=-1;

                    incorrect++;

                }

                    else  if(a38.isSelected()){

                    b10=-1;

                    incorrect++;

                }

                     else  if(a39.isSelected()){

                    b10=2;

                    correct++;

                }

                      else  if(a40.isSelected()){

                    b10=-1;

                    incorrect++;

                }
            
                     else{

                 not++;

             }
               if(a41.isSelected()){

            b11=-1;

            incorrect++;

        }

       else if(a42.isSelected()){

            b11=-1;

            incorrect++;

        }

       else if(a43.isSelected()){

            b11=2;

            correct++;

        }

       else if(a44.isSelected()){

            b11=-1;

            incorrect++;

        }

       else{

           not++;

    

       }

        if(a45.isSelected()){

            b12=-1;

            incorrect++;

        }

       else if(a46.isSelected()){

            b12=-1;

            incorrect++;

        }

       else if(a47.isSelected()){

            b12=-1;

            incorrect++;

        }

       

               else if(a48.isSelected()){

            b12=2;

            correct++;

        }

               else{

                 not++;

             }

              if(a49.isSelected()){

            b13=-1;

            incorrect++;

        }

            

               else if(a50.isSelected()){

            b13=2;

            correct++;

        }

              else  if(a51.isSelected()){

            b13=-1;

            incorrect++;

        }

              else  if(a52.isSelected()){

                    b13=-1;

                    incorrect++;

                }

              else{

                 not++;

             }

                 if(a53.isSelected()){

                    b14=2;

                    correct++;

                }

                 else if(a54.isSelected()){

                    b14=-1;

                    incorrect++;

                }

                 else  if(a55.isSelected()){

                    b14=-1;

                    incorrect++;

                }

                  else  if(a56.isSelected()){

                    b14=-1;

                    incorrect++;

                }

                 else{

                 not++;

             }

                     if(a57.isSelected()){

                    b15=-1;

                    incorrect++;

                }

                    else  if(a58.isSelected()){

                    b15=-1;

                    incorrect++;

                }

                     else  if(a59.isSelected()){

                    b15=2;

                    correct++;

                }

                      else  if(a60.isSelected()){

                    b15=-1;

                    incorrect++;

                }
            
                     else{

                 not++;

             }
                     
        if(a61.isSelected()){

            b16=-1;

            incorrect++;

        }

       else if(a62.isSelected()){

            b16=-1;

            incorrect++;

        }

       else if(a63.isSelected()){

            b16=2;

            correct++;

        }

       else if(a64.isSelected()){

            b16=-1;

            incorrect++;

        }

       else{

           not++;

    

       }

        if(a65.isSelected()){
            
        b17=-1;

            incorrect++;

        }

       else if(a66.isSelected()){

            b17=-1;

            incorrect++;

        }

       else if(a67.isSelected()){

            b17=-1;

            incorrect++;

        }

       

               else if(a68.isSelected()){

            b17=2;

            correct++;

        }

               else{

                 not++;

             }

              if(a69.isSelected()){

            b18=-1;

            incorrect++;

        }

            

               else if(a70.isSelected()){

            b18=2;

            correct++;

        }

              else  if(a71.isSelected()){

            b18=-1;

            incorrect++;

        }

              else  if(a72.isSelected()){

                    b18=-1;

                    incorrect++;

                }

              else{

                 not++;

             }

                 if(a73.isSelected()){

                    b19=2;

                    correct++;

                }

                 else if(a74.isSelected()){

                    b19=-1;

                    incorrect++;

                }

                 else  if(a75.isSelected()){

                    b19=-1;

                    incorrect++;

                }

                  else  if(a76.isSelected()){

                    b19=-1;

                    incorrect++;

                }

                 else{

                 not++;

             }

                     if(a77.isSelected()){

                    b20=-1;

                    incorrect++;

                }

                    else  if(a78.isSelected()){

                    b20=-1;

                    incorrect++;

                }

                     else  if(a79.isSelected()){

                    b20=2;

                    correct++;

                }

                      else  if(a80.isSelected()){

                    b20=-1;

                    incorrect++;

                }
            
                     else{

                 not++;

             }
       int Total=b1+b2+b3+b4+b5+b6+b7+b8+b9+b10+b11+b12+b13+b14+b15+b16+b17+b18+b19+b20;
          ResultScreen q1=new ResultScreen();
        q1.setValueInTextField(Total,correct,incorrect,not);
        q1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void a37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a37ActionPerformed

    private void a65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a65ActionPerformed

    private void a69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a69ActionPerformed

    private void a72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a72ActionPerformed
        
    }//GEN-LAST:event_a72ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a10;
    private javax.swing.JRadioButton a11;
    private javax.swing.JRadioButton a12;
    private javax.swing.JRadioButton a13;
    private javax.swing.JRadioButton a14;
    private javax.swing.JRadioButton a15;
    private javax.swing.JRadioButton a16;
    private javax.swing.JRadioButton a17;
    private javax.swing.JRadioButton a18;
    private javax.swing.JRadioButton a19;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a20;
    private javax.swing.JRadioButton a21;
    private javax.swing.JRadioButton a22;
    private javax.swing.JRadioButton a23;
    private javax.swing.JRadioButton a24;
    private javax.swing.JRadioButton a25;
    private javax.swing.JRadioButton a26;
    private javax.swing.JRadioButton a27;
    private javax.swing.JRadioButton a28;
    private javax.swing.JRadioButton a29;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a30;
    private javax.swing.JRadioButton a31;
    private javax.swing.JRadioButton a32;
    private javax.swing.JRadioButton a33;
    private javax.swing.JRadioButton a34;
    private javax.swing.JRadioButton a35;
    private javax.swing.JRadioButton a36;
    private javax.swing.JRadioButton a37;
    private javax.swing.JRadioButton a38;
    private javax.swing.JRadioButton a39;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a40;
    private javax.swing.JRadioButton a41;
    private javax.swing.JRadioButton a42;
    private javax.swing.JRadioButton a43;
    private javax.swing.JRadioButton a44;
    private javax.swing.JRadioButton a45;
    private javax.swing.JRadioButton a46;
    private javax.swing.JRadioButton a47;
    private javax.swing.JRadioButton a48;
    private javax.swing.JRadioButton a49;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton a50;
    private javax.swing.JRadioButton a51;
    private javax.swing.JRadioButton a52;
    private javax.swing.JRadioButton a53;
    private javax.swing.JRadioButton a54;
    private javax.swing.JRadioButton a55;
    private javax.swing.JRadioButton a56;
    private javax.swing.JRadioButton a57;
    private javax.swing.JRadioButton a58;
    private javax.swing.JRadioButton a59;
    private javax.swing.JRadioButton a6;
    private javax.swing.JRadioButton a60;
    private javax.swing.JRadioButton a61;
    private javax.swing.JRadioButton a62;
    private javax.swing.JRadioButton a63;
    private javax.swing.JRadioButton a64;
    private javax.swing.JRadioButton a65;
    private javax.swing.JRadioButton a66;
    private javax.swing.JRadioButton a67;
    private javax.swing.JRadioButton a68;
    private javax.swing.JRadioButton a69;
    private javax.swing.JRadioButton a7;
    private javax.swing.JRadioButton a70;
    private javax.swing.JRadioButton a71;
    private javax.swing.JRadioButton a72;
    private javax.swing.JRadioButton a73;
    private javax.swing.JRadioButton a74;
    private javax.swing.JRadioButton a75;
    private javax.swing.JRadioButton a76;
    private javax.swing.JRadioButton a77;
    private javax.swing.JRadioButton a78;
    private javax.swing.JRadioButton a79;
    private javax.swing.JRadioButton a8;
    private javax.swing.JRadioButton a80;
    private javax.swing.JRadioButton a9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
