
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class AdminResister extends javax.swing.JFrame {

    /**
     * Creates new form AdminResister
     */
    public AdminResister() {
        initComponents();
    }
    /*private boolean validateFullName(String name) {
    String regex = "^[a-zA-Z]+$"; 
    return name.matches(regex);
}*/
    private boolean validateAadharNumber(String aadharNumber) {
   
    return aadharNumber.matches("\\d{12}") && !aadharNumber.matches("0{12}");
}
    private boolean isValidPassword(String pass) {
    String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{6,}$";
    return pass.matches(regex);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ac = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        ps = new javax.swing.JPasswordField();
        cps = new javax.swing.JPasswordField();
        name = new javax.swing.JTextField();
        aadhar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Registration");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Admin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        ac.setBackground(new java.awt.Color(255, 204, 0));
        ac.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ac.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Authentication Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        un.setBackground(new java.awt.Color(255, 204, 0));
        un.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        un.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter a UserName", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        ps.setBackground(new java.awt.Color(255, 204, 0));
        ps.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ps.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Your Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        cps.setBackground(new java.awt.Color(255, 204, 0));
        cps.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cps.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirm Your Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        name.setBackground(new java.awt.Color(255, 204, 0));
        name.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        aadhar.setBackground(new java.awt.Color(255, 204, 0));
        aadhar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        aadhar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Aadhar no", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(un, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(ac)
                    .addComponent(ps)
                    .addComponent(cps)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aadhar))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(aadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(un, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ps, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cps, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 460, 560));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 460, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BAck arrow.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4back(evt);
                jLabel4back1(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin regd.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String N=name.getText();
       String AA=aadhar.getText();
        String AC=ac.getText();
       String UN=un.getText();
       String PS=ps.getText();
       String CPS=cps.getText();
       String Acode1="Pradhan@123";
       if(N.isEmpty()&&AA.isEmpty()&&AC.isEmpty()&&PS.isEmpty()){
           JOptionPane.showMessageDialog(null,"Fields are Can't blank");
       }else if(AA.isEmpty()){
           JOptionPane.showMessageDialog(null,"Fields are Can't blank");
       }else if(AC.isEmpty()){
           JOptionPane.showMessageDialog(null,"Fields are Can't blank");
       }else if(PS.isEmpty()){
           JOptionPane.showMessageDialog(null,"Fields are Can't blank");
       }else if(CPS.isEmpty()){
           JOptionPane.showMessageDialog(null,"Fields are Can't blank");
       }
       /*if(!validateFullName(N)){
           JOptionPane.showMessageDialog(null,"Enter your full name correctly");
       }*/
        else if(!validateAadharNumber(AA)){
           JOptionPane.showMessageDialog(null,"Enter 12 digits aadhar number correctly");
       }
       else if (!AC.equals(Acode1)) {
        JOptionPane.showMessageDialog(null, "Please enter correct Authentication Id");
    }
      
         else if(!isValidPassword(PS)){
           JOptionPane.showMessageDialog(null,"Password should be the combination of lowercase, uppercase, digits, and special characters");
       }
       
       else if(!PS.equals(CPS)){
           JOptionPane.showMessageDialog(null,"Password Missmatched");
       }
       else{
             try{
              Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","Pradhan@123");
             PreparedStatement ps=con.prepareStatement("insert into ProjectAdminData values(?,?,?,?,?)");
            ps.setString(1,N );
            ps.setString(2, AA);
            ps.setString(3, AC);
            ps.setString(4, UN);
            ps.setString(5, PS);
             int r= ps.executeUpdate();
           if(r>0){
                JOptionPane.showMessageDialog(null,"Registration Successful"+"\n"+"please login");
                AdminLogin al=new AdminLogin();
                al.setVisible(true);
                this.setVisible(false);
        
           }else{
               JOptionPane.showMessageDialog(null,"Something went wrong while updating please try again");
           }
          
          }catch(Exception e){
              e.printStackTrace();
          }
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4back(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4back
        AdminLogin Al=new AdminLogin();
        Al.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4back

    private void jLabel4back1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4back1
        AdminLogin Al=new AdminLogin();
        Al.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4back1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminResister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminResister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminResister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminResister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminResister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar;
    private javax.swing.JTextField ac;
    private javax.swing.JPasswordField cps;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField ps;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
