
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class StudentChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form StudentChangePassword
     */
    public StudentChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        oldpassword = new javax.swing.JPasswordField();
        newpassword = new javax.swing.JPasswordField();
        cpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("RESET");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        username.setBackground(new java.awt.Color(255, 204, 0));
        username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USER NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        oldpassword.setBackground(new java.awt.Color(255, 204, 0));
        oldpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oldpassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OLD PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        newpassword.setBackground(new java.awt.Color(255, 204, 0));
        newpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newpassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NEW PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        cpassword.setBackground(new java.awt.Color(255, 204, 0));
        cpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cpassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONFIRM NEW PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(oldpassword)
                    .addComponent(newpassword)
                    .addComponent(cpassword))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 480, 460));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CHANGE PASSWORD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 603, 480, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BAck arrow.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin regd.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      /* String UN=username.getText();
        String OP=oldpassword.getText();
        String NP=newpassword.getText();
        String CP=cpassword.getText();
     if(UN.isEmpty()&&OP.isEmpty()&&NP.isEmpty()&&CP.isEmpty()){
            JOptionPane.showMessageDialog(null,"All Fields are mandatory!!");
        }else if(OP.isEmpty()){
            JOptionPane.showMessageDialog(null," enter old password ");
        }else if(NP.isEmpty()){
             JOptionPane.showMessageDialog(null," enter new password ");
        }else if(CP.isEmpty()){
             JOptionPane.showMessageDialog(null," enter confirm password ");
        }else if(!NP.equals(CP)){
             JOptionPane.showMessageDialog(null," new password and confirm password are not matched ");
        }else if(OP.equals(NP)){
            JOptionPane.showMessageDialog(null," You can't use your old password");
   
        }else{
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection cn2 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "Pradhan@123");
        Statement stm=cn2.createStatement();
        ResultSet r1=stm.executeQuery("select * from StudentDB");
        PreparedStatement ps2=cn2.prepareStatement("update StudentDB SET NEWPASSWORD=? where REGDNO=?");
        while(r1.next()){
            if(!OP.equals(r1.getString(10)) && !UN.equals(r1.getString(1))){
           JOptionPane.showMessageDialog(null,"Invalid username and password");
           
       }
      else if(OP.equals(r1.getString(10)) && UN.equals(r1.getString(1))){
        ps2.setString(1,NP);
        ps2.setString(2,UN);
        
         int r= ps2.executeUpdate();
        if(r>0){
                JOptionPane.showMessageDialog(null,"Password Update Successful");
           }else{
               JOptionPane.showMessageDialog(null,"Something went wrong while updating please try again");
           }}
       
       else if(!UN.equals(r1.getString(1))){
           JOptionPane.showMessageDialog(null,"Invalid username");
       }
       else{
           JOptionPane.showMessageDialog(null,"Invalid password");
       }
        }}catch(Exception e){
            e.printStackTrace();
        }
        }*/
                                            
    String UN = username.getText();
    String OP = oldpassword.getText();
    String NP = newpassword.getText();
    String CP = cpassword.getText();
    
    if (UN.isEmpty() || OP.isEmpty() || NP.isEmpty() || CP.isEmpty()) {
        JOptionPane.showMessageDialog(null, "All Fields are mandatory!!");
    } else if (!OP.equals(getOldPasswordFromDatabase(UN))) {
        JOptionPane.showMessageDialog(null, "Please kindly check your username or password");
    }
    else if (!NP.equals(CP)) {
        JOptionPane.showMessageDialog(null, "New password and confirm password do not match");
    } else if (OP.equals(NP)) {
        JOptionPane.showMessageDialog(null, "You can't use your old password");
    } else {
        if (updatePasswordInDatabase(UN, NP)) {
            JOptionPane.showMessageDialog(null, "Password Update Successful");
        } else {
            JOptionPane.showMessageDialog(null, "Something went wrong while updating. Please try again.");
        }
    }
}

private String getOldPasswordFromDatabase(String username) {
    String oldPassword = ""; // Initialize the oldPassword variable
    
    try {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "Pradhan@123");
        
        String query = "SELECT NEWPASSWORD FROM StudentDB WHERE REGDNO = ?";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        preparedStatement.setString(1, username);
        
        ResultSet resultSet = preparedStatement.executeQuery();
        
        if (resultSet.next()) {
            oldPassword = resultSet.getString("NEWPASSWORD");
        }
        
        resultSet.close();
        preparedStatement.close();
        connection.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    return oldPassword;
}


private boolean updatePasswordInDatabase(String username, String newPassword) {
    try {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection cn2 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "Pradhan@123");
        PreparedStatement ps2 = cn2.prepareStatement("UPDATE StudentDB SET NEWPASSWORD=? WHERE REGDNO=?");
        ps2.setString(1, newPassword);
        ps2.setString(2, username);
        int rowsAffected = ps2.executeUpdate();
        return rowsAffected > 0;
    } catch (Exception e) {
        e.printStackTrace();
        return false;
    }


       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        StudentLoginPage sl=new StudentLoginPage();
        sl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JPasswordField oldpassword;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
