
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class UpdateStudent extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStudent
     */
    public UpdateStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        s = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        ps = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        regd = new javax.swing.JLabel();
        r1 = new javax.swing.JTextField();
        r2 = new javax.swing.JTextField();
        n1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "State", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 460, 80));

        p.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone No", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 460, 80));

        e.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        getContentPane().add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 460, 80));

        d.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DOB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 460, 80));

        ps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ps.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        getContentPane().add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 460, 80));

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, 110, 30));
        getContentPane().add(regd, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1710, 920));

        r1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Student Registration No.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 460, 80));

        r2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Student Registration No.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 460, 80));

        n1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 460, 80));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 22, 460, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String FNAME=regd.getText();
      String REGDNO=regd.getText();
      String PHONENO=p.getText();
      String DOB=d.getText();
       String STATE=s.getText();
      String EMAIL=e.getText();
      String PASSWORD=ps.getText();
     
      if(FNAME.isEmpty()||REGDNO.isEmpty()||PHONENO.isEmpty()||EMAIL.isEmpty()||STATE.isEmpty()|| PASSWORD.isEmpty()){
          JOptionPane.showMessageDialog(null,"Please Enter Required fields");
      }else if(REGDNO.isEmpty()){
           JOptionPane.showMessageDialog(null,"Please Enter Registration No");
      }else if(PHONENO.isEmpty()){
          JOptionPane.showMessageDialog(null,"Please Enter Phone no");
      }
      else if(PHONENO.length()>10||PHONENO.length()<10){
          JOptionPane.showMessageDialog(null,"Please Enter a valid mobile no");
      }else if(EMAIL.isEmpty()){
          JOptionPane.showMessageDialog(null,"Please Enter Email");
          
      }else if(!PASSWORD.equals(PASSWORD)){
           JOptionPane.showMessageDialog(null,"Password must be same");
      }else{
           try{
              Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","Pradhan@123");
             PreparedStatement ps=con.prepareStatement("UPDATE StudentDB set FULLNAME=?,PHONENO=?,DOB=?,EMAIL=?,STATE=?,NEWPASSWORD=? where REGDNO=?");
            ps.setString(1,FNAME );
            ps.setString(2,PHONENO );
            ps.setString(3,DOB );
            ps.setString(4, STATE);
            ps.setString(5, EMAIL);
            ps.setString(6, PASSWORD);
            ps.setString(7, REGDNO);
           int r= ps.executeUpdate();
           if(r>0){
                JOptionPane.showMessageDialog(null,"Update Successful");
           }else{
               JOptionPane.showMessageDialog(null,"Something went wrong while updating please try again");
           }
           }catch(Exception e){
               
           }
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField p;
    private javax.swing.JPasswordField ps;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r2;
    private javax.swing.JLabel regd;
    private javax.swing.JTextField s;
    // End of variables declaration//GEN-END:variables
}
